# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_auto_20160825_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('-name',), 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('-name',), 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterField(
            model_name='market',
            name='commission',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='commission_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='currency_of_payments',
            field=models.ManyToManyField(blank=True, to='markets.Currency'),
        ),
        migrations.AlterField(
            model_name='market',
            name='customer_support_channels',
            field=models.ManyToManyField(blank=True, related_name='markets_market_customer_related',
                                         to='markets.SupportChannel'),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_details_upload',
            field=models.ManyToManyField(blank=True, to='markets.UploadMethod',
                                         verbose_name='Product Details upload process'),
        ),
        migrations.AlterField(
            model_name='market',
            name='seller_support_channels',
            field=models.ManyToManyField(blank=True, related_name='markets_market_seller_related',
                                         to='markets.SupportChannel'),
        ),
    ]
