# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='famous_brands_on_marketplace',
            field=models.ManyToManyField(blank=True, to='markets.Brand'),
        ),
    ]
