# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_move_geography_to_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.RemoveField(
            model_name='market',
            name='famous_brands_on_marketplace',
        ),
        migrations.AlterField(
            model_name='market',
            name='countries_served',
            field=models.ManyToManyField(to='geography.Country'),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
