# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0009_market_marketing_merchandising'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='market',
            name='logistics_structure',
        ),
        migrations.AddField(
            model_name='market',
            name='logistics_structure',
            field=models.ManyToManyField(blank=True, to='markets.LogisticsModel'),
        ),
    ]
