# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_create_categories'),
        ('markets', '0011_auto_20160907_1005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.AlterField(
            model_name='market',
            name='product_categories',
            field=models.ManyToManyField(to='products.Category'),
        ),
        migrations.RemoveField(
            model_name='market',
            name='product_type',
        ),
        migrations.AddField(
            model_name='market',
            name='product_type',
            field=models.ManyToManyField(blank=True, to='products.Type'),
        ),
    ]
