# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0016_auto_20160907_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='payment_terms_days_notes',
        ),
        migrations.AddField(
            model_name='market',
            name='deposit_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='deposit_needed',
            field=models.BooleanField(default=False, verbose_name='Pricing Fees - Deposit/Bond Needed'),
        ),
        migrations.AlterField(
            model_name='market',
            name='currency_of_payments',
            field=models.ManyToManyField(blank=True, to='markets.Currency',
                                         verbose_name='Payment terms - Currency of payments'),
        ),
        migrations.AlterField(
            model_name='market',
            name='payment_terms_days',
            field=models.IntegerField(blank=True, help_text='in days', null=True,
                                      verbose_name='Payment terms - sale to payment duration'),
        ),
    ]
