# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0017_auto_20160907_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='membership_fees_notes',
        ),
        migrations.AddField(
            model_name='market',
            name='membership_fees_frequency',
            field=models.CharField(blank=True, max_length=1, null=True, choices=[
                ('D', 'Daily'),
                ('W', 'Weekly'),
                ('M', 'Monthly'),
                ('Q', 'Quarterly'),
                ('Y', 'Yearly')]),
        ),
        migrations.AlterField(
            model_name='market',
            name='membership_fees',
            field=models.IntegerField(help_text='Converted to GBP', verbose_name='Pricing/Fees - Membership fees'),
        ),
    ]
