# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0020_auto_20160907_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='deposit_needed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Pricing Fees - Deposit/Bond Needed'),
        ),
        migrations.AlterField(
            model_name='market',
            name='exclusivity_required',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Exclusivity required'),
        ),
        migrations.AlterField(
            model_name='market',
            name='fee_per_listing',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Pricing/Fees - Fee per Listing'),
        ),
        migrations.AlterField(
            model_name='market',
            name='local_bank_account_needed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Local Bank Account Needed'),
        ),
        migrations.AlterField(
            model_name='market',
            name='local_incorporation_needed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Local Incorporation Needed'),
        ),
        migrations.AlterField(
            model_name='market',
            name='local_return_address_required',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Local return address required?'),
        ),
        migrations.AlterField(
            model_name='market',
            name='payment_terms_rate_fixed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Payment Terms - Exchange rate fixed'),
        ),
        migrations.AlterField(
            model_name='market',
            name='registration_fees',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Pricing/Fees - Registration'),
        ),
        migrations.AlterField(
            model_name='market',
            name='shipping_tracking_required',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Shipping Tracking Required'),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_application_process',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Translation Needed - Application process'),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_product_content',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Translation Needed - Product content'),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_seller_support',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Translation Needed - Seller support'),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_verbal',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Translation Needed - Negotiation'),
        ),
    ]
