# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0023_populate_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
