# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0028_auto_20161014_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='countries_served',
            field=models.ManyToManyField(blank=True, to='geography.Country', verbose_name='Operating Countries'),
        ),
        migrations.AlterField(
            model_name='market',
            name='deposit_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='market',
            name='membership_fees',
            field=models.FloatField(default=0, help_text='Converted to GBP',
                                    verbose_name='Pricing/Fees - Membership fees'),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_categories',
            field=models.ManyToManyField(blank=True, to='products.Category'),
        ),
    ]
