# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0029_auto_20161014_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='deposit_needed',
        ),
    ]
