# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0030_remove_market_deposit_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='deposit_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
    ]
