# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0031_market_deposit_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='commission',
        ),
        migrations.AddField(
            model_name='market',
            name='commission_lower',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='commission_upper',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
