# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 12:07
from __future__ import unicode_literals

from django.db import migrations, connections


def default_currency(apps, schema_editor):
    # Do nothing if we are using the test DB (i.e. performing unit tests)
    if connections.databases['default']['NAME'][:4] == 'test':
        return

    Market = apps.get_model('markets', 'Market')
    Currency = apps.get_model('markets', 'Currency')

    try:
        default_currency = Currency.objects.all()[0]
    except IndexError:
        default_currency = Currency.objects.create(name="GBP", symbol="£")

    for market in Market.objects.filter(membership_fees__gt=0, membership_fees_currency__isnull=True):
        market.membership_fees_currency = default_currency
        market.save()

    for market in Market.objects.filter(deposit_amount__gt=0, deposit_currency__isnull=True):
        market.deposit_currency = default_currency
        market.save()


def delete_currency(apps, schema_editor):
    Market = apps.get_model('markets', 'Market')

    for market in Market.objects.all():
        market.membership_fees_currency = None
        market.deposit_currency = None
        market.save()


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0034_auto_20161019_1039'),
    ]

    operations = [
        migrations.RunPython(default_currency, reverse_code=delete_currency),
    ]
