# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0036_remove_market_seller_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerModel',
        ),
    ]
