# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-26 15:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0039_auto_20161026_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='dit_advisor_tip',
            field=models.TextField(blank=True, null=True,
                                   verbose_name='Department of International Trade advisor tip'),
        ),
        migrations.AlterField(
            model_name='market',
            name='exclusivity_required',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Product exclusivity required'),
        ),
        migrations.AlterField(
            model_name='market',
            name='fee_per_listing',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='Fee per Listing'),
        ),
        migrations.AlterField(
            model_name='market',
            name='local_bank_account_needed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='A local bank account'),
        ),
        migrations.AlterField(
            model_name='market',
            name='local_incorporation_needed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='A local company'),
        ),
        migrations.AlterField(
            model_name='market',
            name='local_return_address_required',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='A local address to handle returns?'),
        ),
        migrations.AlterField(
            model_name='market',
            name='membership_fees',
            field=models.FloatField(default=0, verbose_name='Membership fees'),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_details_upload',
            field=models.ManyToManyField(blank=True, to='markets.UploadMethod',
                                         verbose_name='Upload product details via'),
        ),
        migrations.AlterField(
            model_name='market',
            name='registration_fees',
            field=models.FloatField(default=0, verbose_name='One off registration fee'),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_application_process',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='To apply to join'),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_product_content',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='For product content'),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_seller_support',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='For seller support'),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_verbal',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False,
                                      verbose_name='To negotiate with the marketplace'),
        ),
        migrations.AlterField(
            model_name='market',
            name='ukti_terms',
            field=ckeditor.fields.RichTextField(blank=True, null=True,
                                                verbose_name='Department of International Trade special terms'),
        ),
    ]
