# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 13:43
from __future__ import unicode_literals

from django.db import migrations, models
from core.utils import delete_model_duplicates


def delete_duplicates(apps, schema_editor):
    Model = apps.get_model('markets', 'Brand')
    delete_model_duplicates(Model, 'name')
    Model = apps.get_model('markets', 'Currency')
    delete_model_duplicates(Model, 'name')
    Model = apps.get_model('markets', 'LogisticsModel')
    delete_model_duplicates(Model, 'name')
    Model = apps.get_model('markets', 'SupportChannel')
    delete_model_duplicates(Model, 'name')
    Model = apps.get_model('markets', 'UploadMethod')
    delete_model_duplicates(Model, 'name')


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0040_auto_20161026_1517'),
    ]

    operations = [
        migrations.RunPython(delete_duplicates),
    ]
