# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0043_auto_20161027_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='signup_address',
            field=models.URLField(blank=True, null=True, verbose_name='Explore the marketplace'),
        ),
    ]
