# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0047_load_intial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('code',), 'verbose_name_plural': 'Currencies'},
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='name',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
    ]
