# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0051_publish_markets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='published',
        ),
    ]
