# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0055_auto_20170117_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='local_bank_account_needed_notes',
        ),
        migrations.RemoveField(
            model_name='market',
            name='local_return_address_required_notes',
        ),
        migrations.RemoveField(
            model_name='market',
            name='translation_application_process_notes',
        ),
        migrations.RemoveField(
            model_name='market',
            name='translation_product_content_notes',
        ),
        migrations.RemoveField(
            model_name='market',
            name='translation_seller_support_notes',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='local_bank_account_needed_notes',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='local_return_address_required_notes',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='translation_application_process_notes',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='translation_product_content_notes',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='translation_seller_support_notes',
        ),
    ]
