# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0063_auto_20170824_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
