# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0064_auto_20190116_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='dit_special_terms_summary',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='publishedmarket',
            name='dit_special_terms_summary',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
