# Generated by Django 2.2.19 on 2021-04-28 09:12

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0065_auto_20190426_1255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logo",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "400x302",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text="Use cropping tool to cut the image to the right format. Always leave enough                                          white space around the edges and try to keep the largest possible size for                                          good image quality.",
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="image",
            field=models.ImageField(
                help_text="After choosing an image to upload click 'Save' to access the                                                    'Cropping' tool and edit the image",
                null=True,
                upload_to="",
            ),
        ),
    ]
