# Generated by Django 3.2.19 on 2023-11-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0067_alter_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(help_text='After choosing an image to upload click "Save" to access the                                                    "Cropping" tool and edit the image', null=True, upload_to=''),
        ),
    ]
