# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='payment_terms_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
