# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0010_auto_20160907_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='market',
            name='platform_type',
        ),
        migrations.AlterField(
            model_name='market',
            name='countries_served',
            field=models.ManyToManyField(to='geography.Country', verbose_name='Operating Countries'),
        ),
        migrations.AlterField(
            model_name='market',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='e-Marketplace Description'),
        ),
        migrations.AddField(
            model_name='market',
            name='seller_model',
            field=models.ManyToManyField(blank=True, to='markets.SellerModel'),
        ),
    ]
