# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_prohibiteditem'),
        ('markets', '0012_auto_20160907_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='prohibited_items',
            field=models.ManyToManyField(blank=True, to='products.ProhibitedItem'),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_type',
            field=models.ManyToManyField(blank=True, to='products.Type', verbose_name='Product Positioning'),
        ),
        migrations.AlterField(
            model_name='market',
            name='web_traffic',
            field=models.CharField(blank=True, help_text='in millions', max_length=30, null=True,
                                   verbose_name='Number of registered users'),
        ),
    ]
