# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0013_auto_20160907_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='customer_support_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='seller_support_hours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
