# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0014_auto_20160907_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='translation_customer_service_notes',
            new_name='translation_seller_support_notes',
        ),
        migrations.RemoveField(
            model_name='market',
            name='translation_customer_service',
        ),
        migrations.AddField(
            model_name='market',
            name='translation_seller_support',
            field=models.BooleanField(default=False, verbose_name='Translation Needed - Seller support'),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_product_content',
            field=models.BooleanField(default=False, verbose_name='Translation Needed - Product content'),
        ),
        migrations.AlterField(
            model_name='market',
            name='translation_verbal',
            field=models.BooleanField(default=False, verbose_name='Translation Needed - Negotiation'),
        ),
    ]
