# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0015_auto_20160907_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='product_details_upload_notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='market',
            name='exclusivity_required',
            field=models.BooleanField(default=False, verbose_name='Exclusivity required'),
        ),
    ]
