# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-14 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0021_auto_20160907_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
