# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 12:37
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    if not schema_editor.connection.alias == 'default':
        return

    Market = apps.get_model('markets', 'Market')

    for market in Market.objects.all():
        market.slug = slugify(market.name)
        market.save()


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0022_auto_20160914_1104'),
    ]

    operations = [
        migrations.RunPython(populate_slugs),
    ]
