# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-05 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0024_auto_20160914_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='dit_advisor_tip',
            field=models.TextField(blank=True, null=True, verbose_name='DIT Advisor tip'),
        ),
        migrations.AlterField(
            model_name='market',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='e-Marketplace Description'),
        ),
    ]
