# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 11:26
from __future__ import unicode_literals

import os

from django.db import migrations, connections
from django.core.management import call_command

fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))


def load_fixture(apps, schema_editor):
    if connections.databases['default']['NAME'][:4] == 'test':
        return

    fixture_filename = 'initial_0002.json'
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    call_command('loaddata', fixture_file)


def unload_fixture(apps, schema_editor):
    call_command('flush', interactive=False)
    fixture_filename = 'initial_0001.json'
    fixture_file = os.path.join(fixture_dir, fixture_filename)
    call_command('loaddata', fixture_file)


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0025_auto_20161005_1002'),
        ('products', '0004_load_intial_data'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
