# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0027_auto_20161012_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='description',
            field=models.TextField(default='Placeholder', verbose_name='e-Marketplace Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='market',
            name='web_address',
            field=models.URLField(default='www.example.com'),
            preserve_default=False,
        ),
    ]
