# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0032_auto_20161018_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='deposit_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='markets_market_deposit_currency', to='markets.Currency'),
        ),
        migrations.AddField(
            model_name='market',
            name='membership_fees_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='markets_market_membership_fees_currency', to='markets.Currency'),
        ),
    ]
