# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0035_auto_20161019_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='seller_model',
        ),
    ]
