# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0042_auto_20161027_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.AddField(
            model_name='market',
            name='seller_model',
            field=models.ManyToManyField(blank=True, to='markets.SellerModel'),
        ),
    ]
