# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0044_market_signup_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='deposit_amount',
            new_name='deposit',
        ),
    ]
