# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0045_auto_20161028_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ('name',), 'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='sellermodel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='supportchannel',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='uploadmethod',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
