# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-19 14:07
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def setup_versions(apps, schema_editor):
    call_command('createinitialrevisions')


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0049_published_market_model'),
    ]

    operations = [
        migrations.RunPython(setup_versions),
    ]
