# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0053_auto_20170117_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='local_bank_account_needed',
        ),
        migrations.RemoveField(
            model_name='market',
            name='local_incorporation_needed',
        ),
        migrations.RemoveField(
            model_name='market',
            name='local_incorporation_needed_notes',
        ),
        migrations.RemoveField(
            model_name='market',
            name='local_return_address_required',
        ),
        migrations.RemoveField(
            model_name='market',
            name='translation_application_process',
        ),
        migrations.RemoveField(
            model_name='market',
            name='translation_product_content',
        ),
        migrations.RemoveField(
            model_name='market',
            name='translation_seller_support',
        ),
        migrations.RemoveField(
            model_name='market',
            name='translation_verbal',
        ),
        migrations.RemoveField(
            model_name='market',
            name='translation_verbal_notes',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='local_bank_account_needed',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='local_incorporation_needed',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='local_incorporation_needed_notes',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='local_return_address_required',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='translation_application_process',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='translation_product_content',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='translation_seller_support',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='translation_verbal',
        ),
        migrations.RemoveField(
            model_name='publishedmarket',
            name='translation_verbal_notes',
        ),
    ]
