# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-17 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import ckeditor


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0054_auto_20170117_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='commission_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='deposit_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='market',
            name='exclusivity_required_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='market',
            name='fee_per_listing_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='market',
            name='payment_terms_rate_fixed_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='market',
            name='product_details_upload_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='market',
            name='registration_fees_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='market',
            name='shipping_tracking_required_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='commission_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='deposit_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='exclusivity_required_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='fee_per_listing_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='payment_terms_rate_fixed_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='product_details_upload_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='registration_fees_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='shipping_tracking_required_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='market',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='e-Marketplace Description'),
        ),
        migrations.AlterField(
            model_name='market',
            name='dit_advisor_tip',
            field=ckeditor.fields.RichTextField(blank=True, null=True,
                                                verbose_name='Department of International Trade advisor tip'),
        ),
        migrations.AlterField(
            model_name='market',
            name='logistics_structure_notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='e-Marketplace Description'),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='dit_advisor_tip',
            field=ckeditor.fields.RichTextField(blank=True, null=True,
                                                verbose_name='Department of International Trade advisor tip'),
        ),
        migrations.AlterField(
            model_name='publishedmarket',
            name='logistics_structure_notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
