# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 14:37
from __future__ import unicode_literals

import base64
import os

from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify
import image_cropping.fields
from django.core.files import File
from PIL import Image


def export_images(apps, schema_editor):
    Logo = apps.get_model('markets', 'Logo')

    for logo in Logo.objects.all():
        filename = '{0}.png'.format(slugify(logo.name))

        with open(filename, 'wb') as logo_image:
            image_data = base64.b64decode(logo._encoded_data[22:])
            logo_image.write(image_data)

        with open(filename, 'rb') as logo_image:
            logo.image.save(filename, File(logo_image), save=True)

        with Image.open(filename) as im:
            width, height = im.size
            logo.cropping = '0,0,{0},{1}'.format(width, height)

        os.remove(filename)
        logo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0057_auto_20170228_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '400x302', adapt_rotation=False, allow_fullsize=False,
                                                        free_crop=False, help_text=None, hide_image_field=False,
                                                        size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='logo',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.RunPython(export_images),
    ]
