search_options = {
    'categories': [
        'Animals & Pet Supplies',
        'Arts & Entertainment',
        'Baby & Toddler',
        'Business & Industrial',
        'Cameras & Optics',
        'Clothing & Accessories',
        'Electronics',
        'Food, Beverages & Tobacco',
        'Furniture',
        'Hardware',
        'Health & Beauty',
        'Home & Garden',
        'Luggage & Bags',
        'Mature',
        'Media',
        'Office Supplies',
        'Religious & Ceremonial',
        'Software',
        'Sporting Goods',
        'Toys & Games',
        'Vehicles & Parts'
    ],
    'countries': [
        'China',
        'United Kingdom',
        'Spain',
        'France',
        'Germany',
        'Italy',
        'Netherlands',
        'New Zealand',
        'Poland',
        'India',
        'Japan',
        'Global',
        'Mexico',
        'Belgium',
        'United States',
        'Singapore',
        'Austria',
        'Australia',
        'Russia'
    ]
}

market_slugs = [
    'zalora',
    'xiu',
    'westwing',
    'vip-shop',
    'trademe',
    'tmall-global',
    'the-iconic',
    'spartoo',
    'shangpin',
    'sfbest',
    'royal-mail-t-mall',
    'rakuten',
    'privalia',
    'otto',
    'newegg-inc',
    'mercado-libre',
    'kaola',
    'jd-worldwide',
    'jack-russell-emporium-on-jdcom',
    'flipkart',
    'etsy',
    'ebay',
    'ctrip',
    'cdiscount',
    'british-pavilion-on-1688com',
    'amazon-usa',
    'amazon-spain',
    'amazon-japan',
    'amazon-italy',
    'amazon-india',
    'amazon-germany',
    'amazon-france',
    'amazon-china',
    'amazon-canada',
    'allegro',
    'alibaba-direct',
    '1688com'
]
