FROM ukti/docker-ukpaas-deploy-ubuntu:latest

RUN mkdir -p /project/app
WORKDIR /project

# Install required packages
RUN apt-get update 
RUN apt-get install -y curl
RUN apt-get install -y wget
RUN apt-get install -y libpq-dev
RUN apt-get install -y libjpeg8-dev
RUN apt-get install -y libfontconfig

## Install node
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get install -y nodejs build-essential

# Install dockerize https://github.com/jwilder/dockerize
ENV DOCKERIZE_VERSION v0.4.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

# Add project frontend build files, and build
ADD gulpfile.babel.js .babelrc karma.conf.js package.json projectpath.babel.js /project/
RUN npm install
# Bug in npm requires a rebuild of node-sass
RUN npm rebuild node-sass

# Add project python requirements and install
ADD scripts/requirements.txt /project/
RUN pip3 install -r /project/requirements.txt

###########################
# END OF COMMON DOCKERFILE (TODO: put this image in a registry)
###########################

# Additional pacakages needed for end to end tests
RUN apt-get install -y default-jre

# Add and install additional python packages for test
ADD scripts/requirements_for_test.txt /project/
RUN pip install -r /project/requirements_for_test.txt

# Copy in necessary files for test run
ADD scripts/docker/run-tests.sh scripts/docker/test.env setup.cfg /project/

# Copy the app source in
ADD app/ /project/app/

# Run tests
CMD ["/project/run-tests.sh"]
