# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_create_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProhibitedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
