# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-03 11:26
from __future__ import unicode_literals

import os

from django.db import migrations
from django.core.management import call_command
from core.utils import safe_load_fixture


fixture_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../fixtures'))


def load_fixture(apps, schema_editor):
    fixture_filename = 'initial_0003.json'
    fixture_path = os.path.join(fixture_dir, fixture_filename)
    safe_load_fixture(apps, fixture_path)


def unload_fixture(apps, schema_editor):
    call_command('flush', interactive=False)
    fixture_filename = 'initial_0002.json'
    fixture_path = os.path.join(fixture_dir, fixture_filename)
    safe_load_fixture(apps, fixture_path)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20161027_1429'),
        ('geography', '0005_load_intial_data'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
