# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models
from django.db import connections


def set_sort_order(apps, schema_editor):
    if connections.databases['default']['NAME'][:4] == 'test':
        return

    Type = apps.get_model('products', 'Type')
    economy = Type.objects.get(name='Economy')
    economy.sort_order = 1
    economy.save()

    midrange = Type.objects.get(name='Mid-Range')
    midrange.sort_order = 2
    midrange.save()

    premium = Type.objects.get(name='Premium')
    premium.sort_order = 3
    premium.save()

    luxury = Type.objects.get(name='Luxury')
    luxury.sort_order = 4
    luxury.save()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_load_intial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('sort_order',)},
        ),
        migrations.RunPython(set_sort_order),
        migrations.AlterField(
            model_name='type',
            name='sort_order',
            field=models.IntegerField(),
        ),
    ]
