# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 16:35
from __future__ import unicode_literals

from django.db import migrations


UNUSED_CATEGORIES = (
    'Mature',
    'Religious & Ceremonial'
)


def delete_unused_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.filter(name__in=UNUSED_CATEGORIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_update_parent_category_naming_format'),
    ]

    operations = [
        migrations.RunPython(delete_unused_categories),
    ]
