# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 12:28
from __future__ import unicode_literals

from django.db import migrations


country_mapping = {
    'Burma': {'name': 'Myanmar (Burma)', 'alternate_name': 'The Republic of the Union of Myanmar'},
    'Swaziland': {'name': 'Eswatini', 'alternate_name': 'Kingdom of Eswatini'},
    'Macedonia': {'name': 'North Macedonia', 'alternate_name': 'Republic of North Macedonia'},
}


def update_country_names(apps, schema_editor):
    # Updating country names to be consistent with countries and territories on data workspace
    # https://data.trade.gov.uk/catalogue/reference-data-sets/reference/countries-and-territories
    Country = apps.get_model('geography', 'Country')
    for original_name, country_details in country_mapping.items():
        try:
            country = Country.objects.get(name=original_name)
            country.name = country_details['name']
            country.alternate_name = country_details['alternate_name']
            country.save()
        except Country.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0007_new_countries_remove_regions'),
    ]

    operations = [
        migrations.RunPython(update_country_names, migrations.RunPython.noop),
    ]
