# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 14:27
from __future__ import unicode_literals

from django.db import migrations
from core.utils import delete_model_duplicates


def delete_duplicates(apps, schema_editor):
    Model = apps.get_model('products', 'Category')
    delete_model_duplicates(Model, 'name')
    Model = apps.get_model('products', 'ProhibitedItem')
    delete_model_duplicates(Model, 'name')
    Model = apps.get_model('products', 'Type')
    delete_model_duplicates(Model, 'name')


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20161014_1539'),
    ]

    operations = [
        migrations.RunPython(delete_duplicates),
    ]
